import { WmoCodeInfo } from '../types';

export const WMO_CODES: Record<number, WmoCodeInfo> = {
  0: {
    code: 0,
    description: 'Clear Sky',
    iconName: 'Sun',
    bgGradientLight: 'from-amber-400/20 via-sky-300/20 to-blue-500/20',
    bgGradientDark: 'from-slate-900 via-indigo-950 to-slate-900',
    isRain: false,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  1: {
    code: 1,
    description: 'Mainly Clear',
    iconName: 'SunDim',
    bgGradientLight: 'from-amber-300/20 via-sky-200/20 to-blue-400/20',
    bgGradientDark: 'from-slate-900 via-indigo-950 to-slate-900',
    isRain: false,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  2: {
    code: 2,
    description: 'Partly Cloudy',
    iconName: 'CloudSun',
    bgGradientLight: 'from-sky-300/30 via-blue-200/20 to-slate-300/30',
    bgGradientDark: 'from-slate-900 via-slate-800 to-indigo-950',
    isRain: false,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  3: {
    code: 3,
    description: 'Overcast',
    iconName: 'Cloud',
    bgGradientLight: 'from-slate-300/40 via-blue-200/30 to-slate-400/30',
    bgGradientDark: 'from-slate-900 via-slate-800 to-zinc-900',
    isRain: false,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  45: {
    code: 45,
    description: 'Foggy',
    iconName: 'CloudFog',
    bgGradientLight: 'from-slate-200/50 via-zinc-300/30 to-slate-400/30',
    bgGradientDark: 'from-zinc-900 via-slate-900 to-zinc-950',
    isRain: false,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  48: {
    code: 48,
    description: 'Depositing Rime Fog',
    iconName: 'CloudFog',
    bgGradientLight: 'from-cyan-200/40 via-slate-300/30 to-blue-300/30',
    bgGradientDark: 'from-zinc-900 via-cyan-950 to-slate-900',
    isRain: false,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  51: {
    code: 51,
    description: 'Light Drizzle',
    iconName: 'CloudDrizzle',
    bgGradientLight: 'from-sky-200/50 via-blue-300/30 to-slate-300/40',
    bgGradientDark: 'from-slate-900 via-sky-950 to-slate-900',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  53: {
    code: 53,
    description: 'Moderate Drizzle',
    iconName: 'CloudDrizzle',
    bgGradientLight: 'from-sky-300/50 via-blue-400/30 to-slate-400/40',
    bgGradientDark: 'from-slate-900 via-sky-950 to-slate-900',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  55: {
    code: 55,
    description: 'Dense Drizzle',
    iconName: 'CloudDrizzle',
    bgGradientLight: 'from-sky-400/40 via-blue-500/30 to-slate-500/40',
    bgGradientDark: 'from-slate-950 via-blue-950 to-slate-900',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  56: {
    code: 56,
    description: 'Light Freezing Drizzle',
    iconName: 'CloudHail',
    bgGradientLight: 'from-cyan-300/40 via-sky-400/30 to-slate-400/40',
    bgGradientDark: 'from-slate-950 via-cyan-950 to-slate-900',
    isRain: true,
    isSnow: true,
    isThunder: false,
    isExtreme: false,
  },
  57: {
    code: 57,
    description: 'Dense Freezing Drizzle',
    iconName: 'CloudHail',
    bgGradientLight: 'from-cyan-400/40 via-sky-500/30 to-slate-500/40',
    bgGradientDark: 'from-slate-950 via-cyan-950 to-slate-900',
    isRain: true,
    isSnow: true,
    isThunder: false,
    isExtreme: false,
  },
  61: {
    code: 61,
    description: 'Slight Rain',
    iconName: 'CloudRain',
    bgGradientLight: 'from-blue-300/40 via-sky-300/30 to-slate-300/40',
    bgGradientDark: 'from-slate-900 via-blue-950 to-slate-900',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  63: {
    code: 63,
    description: 'Moderate Rain',
    iconName: 'CloudRain',
    bgGradientLight: 'from-blue-400/50 via-sky-400/30 to-slate-400/40',
    bgGradientDark: 'from-slate-950 via-blue-950 to-slate-900',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  65: {
    code: 65,
    description: 'Heavy Rain',
    iconName: 'CloudRainWind',
    bgGradientLight: 'from-blue-500/50 via-slate-500/40 to-indigo-500/30',
    bgGradientDark: 'from-slate-950 via-blue-950 to-zinc-950',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: true,
  },
  66: {
    code: 66,
    description: 'Light Freezing Rain',
    iconName: 'CloudHail',
    bgGradientLight: 'from-cyan-300/50 via-blue-400/30 to-slate-400/40',
    bgGradientDark: 'from-slate-950 via-cyan-950 to-slate-900',
    isRain: true,
    isSnow: true,
    isThunder: false,
    isExtreme: false,
  },
  67: {
    code: 67,
    description: 'Heavy Freezing Rain',
    iconName: 'CloudHail',
    bgGradientLight: 'from-cyan-400/50 via-blue-500/30 to-slate-500/40',
    bgGradientDark: 'from-slate-950 via-cyan-950 to-slate-900',
    isRain: true,
    isSnow: true,
    isThunder: false,
    isExtreme: true,
  },
  71: {
    code: 71,
    description: 'Slight Snow Fall',
    iconName: 'Snowflake',
    bgGradientLight: 'from-indigo-100/60 via-sky-200/40 to-slate-200/50',
    bgGradientDark: 'from-slate-950 via-slate-900 to-sky-950',
    isRain: false,
    isSnow: true,
    isThunder: false,
    isExtreme: false,
  },
  73: {
    code: 73,
    description: 'Moderate Snow Fall',
    iconName: 'Snowflake',
    bgGradientLight: 'from-indigo-200/60 via-sky-300/40 to-slate-300/50',
    bgGradientDark: 'from-slate-950 via-indigo-950 to-sky-950',
    isRain: false,
    isSnow: true,
    isThunder: false,
    isExtreme: false,
  },
  75: {
    code: 75,
    description: 'Heavy Snow Fall',
    iconName: 'Snowflake',
    bgGradientLight: 'from-indigo-300/60 via-sky-400/40 to-slate-400/50',
    bgGradientDark: 'from-slate-950 via-indigo-950 to-slate-900',
    isRain: false,
    isSnow: true,
    isThunder: false,
    isExtreme: true,
  },
  77: {
    code: 77,
    description: 'Snow Grains',
    iconName: 'Snowflake',
    bgGradientLight: 'from-indigo-100/60 via-sky-200/40 to-slate-200/50',
    bgGradientDark: 'from-slate-950 via-slate-900 to-sky-950',
    isRain: false,
    isSnow: true,
    isThunder: false,
    isExtreme: false,
  },
  80: {
    code: 80,
    description: 'Slight Rain Showers',
    iconName: 'CloudRain',
    bgGradientLight: 'from-blue-300/40 via-sky-300/30 to-slate-300/40',
    bgGradientDark: 'from-slate-900 via-blue-950 to-slate-900',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  81: {
    code: 81,
    description: 'Moderate Rain Showers',
    iconName: 'CloudRain',
    bgGradientLight: 'from-blue-400/40 via-sky-400/30 to-slate-400/40',
    bgGradientDark: 'from-slate-950 via-blue-950 to-slate-900',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  },
  82: {
    code: 82,
    description: 'Violent Rain Showers',
    iconName: 'CloudRainWind',
    bgGradientLight: 'from-blue-600/40 via-slate-600/40 to-indigo-600/30',
    bgGradientDark: 'from-slate-950 via-blue-950 to-slate-950',
    isRain: true,
    isSnow: false,
    isThunder: false,
    isExtreme: true,
  },
  85: {
    code: 85,
    description: 'Slight Snow Showers',
    iconName: 'Snowflake',
    bgGradientLight: 'from-indigo-200/50 via-sky-200/40 to-slate-200/40',
    bgGradientDark: 'from-slate-950 via-indigo-950 to-slate-900',
    isRain: false,
    isSnow: true,
    isThunder: false,
    isExtreme: false,
  },
  86: {
    code: 86,
    description: 'Heavy Snow Showers',
    iconName: 'Snowflake',
    bgGradientLight: 'from-indigo-300/50 via-sky-300/40 to-slate-300/40',
    bgGradientDark: 'from-slate-950 via-indigo-950 to-slate-900',
    isRain: false,
    isSnow: true,
    isThunder: false,
    isExtreme: true,
  },
  95: {
    code: 95,
    description: 'Thunderstorm',
    iconName: 'CloudLightning',
    bgGradientLight: 'from-amber-500/20 via-purple-600/30 to-slate-800/40',
    bgGradientDark: 'from-slate-950 via-purple-950 to-slate-950',
    isRain: true,
    isSnow: false,
    isThunder: true,
    isExtreme: true,
  },
  96: {
    code: 96,
    description: 'Thunderstorm with Slight Hail',
    iconName: 'CloudLightning',
    bgGradientLight: 'from-amber-500/20 via-purple-700/30 to-slate-800/40',
    bgGradientDark: 'from-slate-950 via-purple-950 to-slate-950',
    isRain: true,
    isSnow: true,
    isThunder: true,
    isExtreme: true,
  },
  99: {
    code: 99,
    description: 'Thunderstorm with Heavy Hail',
    iconName: 'CloudLightning',
    bgGradientLight: 'from-amber-600/20 via-purple-800/40 to-slate-900/50',
    bgGradientDark: 'from-slate-950 via-purple-950 to-slate-950',
    isRain: true,
    isSnow: true,
    isThunder: true,
    isExtreme: true,
  },
};

export function getWmoInfo(code: number, isDay: number = 1): WmoCodeInfo {
  const info = WMO_CODES[code];
  if (info) {
    if (!isDay && (code === 0 || code === 1)) {
      return {
        ...info,
        iconName: 'Moon',
        description: code === 0 ? 'Clear Night' : 'Mostly Clear Night',
      };
    }
    if (!isDay && code === 2) {
      return {
        ...info,
        iconName: 'CloudMoon',
      };
    }
    return info;
  }
  return {
    code,
    description: 'Unknown Conditions',
    iconName: 'Cloud',
    bgGradientLight: 'from-slate-200/50 to-slate-300/50',
    bgGradientDark: 'from-slate-900 to-zinc-900',
    isRain: false,
    isSnow: false,
    isThunder: false,
    isExtreme: false,
  };
}
